spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}
  liquibase:
    change-log: liquibase/changelog-master.xml
    contexts: local
  jpa:
    show-sql: true
